/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import mainpkg.*;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.DecimalFormat;
import java.util.InputMismatchException;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;

/**
 *
 * @author Ana Luísa
 */
public class JanelaProfNotasAluno extends javax.swing.JFrame {

	
	private static Aluno aluno;
	private JanelaProfSelecaoAluno lastWindow;
	private double[] notas = {0, 0, 0, 0};
	private static int d;
	
	public void setLastWindow(JanelaProfSelecaoAluno window){
		this.lastWindow = window;
	}
	
    /**
     * Creates new form NotasAluno
     */
    public JanelaProfNotasAluno(Aluno alunoConsultado, int disciplina) {
    	aluno = alunoConsultado;
    	d= disciplina;
        initComponents();
        recuperarNotasAluno();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCursando = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        media = new javax.swing.JTextField();
        

        jTextField1.setText("jTextField1");
        

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel14.setText("jLabel14");

        jTextField12.setText("jTextField12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notas de "+aluno.getNome(), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("1\u00BA Bimestre:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("2\u00BA Bimestre:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("3\u00BA Bimestre:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Média:");
        
        JLabel lblBimestre = new JLabel();
        lblBimestre.setText("4\u00BA Bimestre:");
        lblBimestre.setFont(new Font("Tahoma", Font.BOLD, 12));

        n1.setBackground(Color.WHITE);
        n1.setFont(new java.awt.Font("Tahoma", 0, 12));
        n1.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		try {
        		  double usrInput= Double.parseDouble(n1.getText());
        		}
        		catch(NumberFormatException exception) {
        		  System.out.println("This is not a double");
        		  n1.setText("");
        		}
        	}
        });

        n2.setBackground(Color.WHITE);
        n2.setFont(new java.awt.Font("Tahoma", 0, 12));
        n2.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		try {
          		  double usrInput= Double.parseDouble(n2.getText());
          		}
          		catch(NumberFormatException exception) {
          		  System.out.println("This is not a double");
          		  n2.setText("");
          		}
        	}
        });

        n3.setBackground(Color.WHITE);
        n3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        n3.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		try {
          		  double usrInput= Double.parseDouble(n3.getText());
          		}
          		catch(NumberFormatException exception) {
          		  System.out.println("This is not a double");
          		  n3.setText("");
          		}
        	}
        });
        n4 = new JTextField();
        n4.setFont(new Font("Tahoma", Font.PLAIN, 12));
        n4.setBackground(Color.WHITE);
        n4.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		try {
          		  double usrInput= Double.parseDouble(n4.getText());
          		}
          		catch(NumberFormatException exception) {
          		  System.out.println("This is not a double");
          		  n4.setText("");
          		}
        	}
        });
        
        media.setBackground(new java.awt.Color(240, 240, 240));
        media.setEditable(false);
        media.setFont(new java.awt.Font("Tahoma", 0, 12));
        
        lblCursando.setText("Cursando");
        lblCursando.setFont(new Font("Dialog", Font.BOLD, 20));
        
        JButton btnVoltar = new JButton("Voltar");
        btnVoltar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		lastWindow.setVisible(true);
        		setVisible(false);
        		try {
					this.finalize();
				} catch (Throwable e) {
					e.printStackTrace();
				}
        	}
        });
        
        JButton btnAlterarNotas = new JButton("Alterar Notas");
        btnAlterarNotas.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bttnAlterarPerformed();
        	}
        });
        
        JButton btnNewButton = new JButton("Enviar Notas");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bttnEnviarPerformed();
        	}
        });
        
        JButton btnVerMdia = new JButton("Confirmar Notas");
        btnVerMdia.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bttnConfirmarPerformed();
        	}
        });
        
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 420, Short.MAX_VALUE)
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 304, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GroupLayout gl_jPanel1 = new GroupLayout(jPanel1);
        gl_jPanel1.setHorizontalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addComponent(btnVoltar)
        			.addPreferredGap(ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
        			.addComponent(btnAlterarNotas)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnNewButton)
        			.addGap(100))
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblCursando, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(6)
        					.addComponent(jLabel12)
        					.addGap(12)
        					.addComponent(media, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(lblBimestre)
        							.addGap(18)
        							.addComponent(n4, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(18)
        							.addComponent(n2, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel11)
        							.addGap(18)
        							.addComponent(n3, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)))
        					.addGap(136))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addComponent(jLabel4)
        					.addGap(18)
        					.addComponent(n1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        		.addGroup(Alignment.LEADING, gl_jPanel1.createSequentialGroup()
        			.addGap(132)
        			.addComponent(btnVerMdia)
        			.addContainerGap(241, Short.MAX_VALUE))
        );
        gl_jPanel1.setVerticalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(15)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel4)
        						.addComponent(n1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(9)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel6)
        						.addComponent(n2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(23)
        					.addComponent(lblCursando)))
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        					.addGroup(gl_jPanel1.createSequentialGroup()
        						.addGap(24)
        						.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        							.addGroup(gl_jPanel1.createSequentialGroup()
        								.addGap(17)
        								.addComponent(jLabel12))
        							.addGroup(gl_jPanel1.createSequentialGroup()
        								.addGap(13)
        								.addComponent(media, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        					.addGroup(gl_jPanel1.createSequentialGroup()
        						.addGap(6)
        						.addComponent(n3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(18)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.TRAILING)
        						.addComponent(n4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel11)
        							.addGap(18)
        							.addComponent(lblBimestre)))))
        			.addPreferredGap(ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        			.addComponent(btnVerMdia)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnAlterarNotas)
        				.addComponent(btnNewButton)
        				.addComponent(btnVoltar)))
        );
        jPanel1.setLayout(gl_jPanel1);
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mudaStatusAluno(double media){
    	if (!n4.getText().equals("") & media >= 6.0){
        	lblCursando.setText("Aprovado");
        }
        else if (!n4.getText().equals("") & media < 6.0){
        	lblCursando.setText("Reprovado");
        }
        else if (n4.getText().equals("")){
        	lblCursando.setText("Cursando");
        }
    }
    
    private void bttnConfirmarPerformed(){
    	System.out.println(n4.getText());
    	if (!n1.getText().equals("")){
    		notas[0] = Double.parseDouble(n1.getText());
    	}
    	else notas[0] = 0.0;
    	if (!n2.getText().equals("")){
    		notas[1] = Double.parseDouble(n2.getText());
    	}
    	else notas[1] = 0.0;
    	if (!n3.getText().equals("")){
    		notas[2] = Double.parseDouble(n3.getText());
    	}
    	else notas[2] = 0.0;
    	if (!n4.getText().equals("")){
    		notas[3] = Double.parseDouble(n4.getText());
    	}
    	else notas[3] = 0.0;
    	
    	if (notas[0] > 10.0 | notas[0] < 0.0){
    		n1.setText("");
    		return;
    	}
    	else if(notas[1] > 10.0 | notas[1] < 0.0){
    		n2.setText("");
    		return;
    	}
    	else if (notas[2] > 10.0 | notas[2] < 0.0){
    		n3.setText("");
    		return;
    	}
    	else if (notas[3] > 10.0 | notas[3] < 0.0){
    		n4.setText("");
    		return;
    	}
    	
    	DecimalFormat numberFormat = new DecimalFormat("#.00");
    	double theMedia = aluno.doMedia(notas[0], notas[1], notas[2], notas[3]);
    	String mediaStr = String.valueOf(numberFormat.format(theMedia));
    	media.setText(mediaStr);
        n1.setEditable(false);
        n1.setBackground(Color.LIGHT_GRAY);
        n2.setEditable(false);
        n2.setBackground(Color.LIGHT_GRAY);
        n3.setEditable(false);
        n3.setBackground(Color.LIGHT_GRAY);
        n4.setEditable(false);
        n4.setBackground(Color.LIGHT_GRAY);
    	mudaStatusAluno(theMedia);
    }
    
    private void bttnAlterarPerformed(){
    	n1.setEditable(true);
        n1.setBackground(Color.WHITE);
        n2.setEditable(true);
        n2.setBackground(Color.WHITE);
        n3.setEditable(true);
        n3.setBackground(Color.WHITE);
        n4.setEditable(true);
        n4.setBackground(Color.WHITE);
    }
    
    private void bttnEnviarPerformed(){
    	if (!n1.getText().equals("")){
    		aluno.setFlag(true, d, 0);
    	}
    	if (!n2.getText().equals("")){
    		aluno.setFlag(true, d, 1);
    	}
    	if (!n3.getText().equals("")){
    		aluno.setFlag(true, d, 2);
    	}
    	if (!n4.getText().equals("")){
    		aluno.setFlag(true, d, 3);
    	}
    	bttnConfirmarPerformed();
    	aluno.setNotas(notas[0], notas[1], notas[2], notas[3], d);
    }
    
    private void recuperarNotasAluno(){
    	String nota = new String();
        if(aluno.getFlag(d,0)){
        	nota = String.valueOf(aluno.getN1(d));
            n1.setText(nota);
            n1.setEditable(false);
            n1.setBackground(Color.LIGHT_GRAY);
        }
        if (aluno.getFlag(d,1)){
        	 nota = String.valueOf(aluno.getN2(d));
             n2.setText(nota);
             n2.setEditable(false);
             n2.setBackground(Color.LIGHT_GRAY);
        }
        if (aluno.getFlag(d,2)){
       	 	nota = String.valueOf(aluno.getN3(d));
            n3.setText(nota);
            n3.setEditable(false);
            n3.setBackground(Color.LIGHT_GRAY);
       }
        if (aluno.getFlag(d,3)){
       	 	nota = String.valueOf(aluno.getN4(d));
            n4.setText(nota);
            n4.setEditable(false);
            n4.setBackground(Color.LIGHT_GRAY);
       }
        DecimalFormat numberFormat = new DecimalFormat("#.00");
        nota = String.valueOf(numberFormat.format(aluno.getMedia(d)));
        media.setText(nota);
        mudaStatusAluno(aluno.getMedia(d));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaProfNotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaProfNotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaProfNotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaProfNotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaProfNotasAluno(aluno, d).setVisible(true);
            }
        });
        
        
    }
    
    
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private JLabel lblCursando;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField media;
    private JTextField n4;
}
