/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import mainpkg.*;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.DecimalFormat;
import java.util.InputMismatchException;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;

/**
 *
 * @author Ana LuÃ­sa
 */
public class JanelaAlunoNotas extends javax.swing.JFrame {

	
	private static Aluno aluno;
	private JanelaAlunoSelecDisciplina lastWindow;
	private double[] notas = {0, 0, 0, 0};
	private static int d;  //variável para amazenar a posição da disciplina na matriz do aluno
	
	public void setLastWindow(JanelaAlunoSelecDisciplina window){
		this.lastWindow = window;
	}
    /**
     * Creates new form NotasAluno
     */
    public JanelaAlunoNotas(Aluno alunoConsultando, int disciplina) {
    	aluno = alunoConsultando;
    	d = disciplina;
        initComponents();
        recuperarNotasAluno();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCursando = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n1.setEditable(false);
        n2 = new javax.swing.JTextField();
        n2.setEditable(false);
        n3 = new javax.swing.JTextField();
        n3.setEditable(false);
        media = new javax.swing.JTextField();
        

        jTextField1.setText("jTextField1");
        

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel14.setText("jLabel14");

        jTextField12.setText("jTextField12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notas de "+aluno.getNome(), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("1\u00BA Bimestre:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("2\u00BA Bimestre:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("3\u00BA Bimestre:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("MÃ©dia:");

        n1.setBackground(Color.LIGHT_GRAY);
        n1.setFont(new java.awt.Font("Tahoma", 0, 12));

        n2.setBackground(Color.LIGHT_GRAY);
        n2.setFont(new java.awt.Font("Tahoma", 0, 12));

        n3.setBackground(Color.LIGHT_GRAY);
        n3.setFont(new java.awt.Font("Tahoma", 0, 12));
        
        n4 = new JTextField();
        n4.setBackground(Color.LIGHT_GRAY);
        n4.setEditable(false);
        n4.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        
        
        media.setBackground(new java.awt.Color(240, 240, 240));
        media.setEditable(false);
        media.setFont(new java.awt.Font("Tahoma", 0, 12));
        
        lblCursando.setText("Cursando");
        lblCursando.setFont(new Font("Dialog", Font.BOLD, 20));
        
        btnVoltar = new JButton("Voltar");
        btnVoltar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		lastWindow.setVisible(true);
        		setVisible(false);
        	}
        });
        
        JLabel lblBimestre = new JLabel();
        lblBimestre.setText("4\u00BA Bimestre:");
        lblBimestre.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        
        
        GroupLayout gl_jPanel1 = new GroupLayout(jPanel1);
        gl_jPanel1.setHorizontalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(10)
        					.addComponent(lblCursando, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblBimestre, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(n4))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addGap(18)
        							.addComponent(n1))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel6)
        								.addComponent(jLabel11))
        							.addGap(18)
        							.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        								.addComponent(n3, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
        								.addComponent(n2, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)))))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel12)
        					.addGap(18)
        					.addComponent(media, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(164)
        					.addComponent(btnVoltar)))
        			.addContainerGap(27, Short.MAX_VALUE))
        );
        gl_jPanel1.setVerticalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(24)
        					.addComponent(lblCursando))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addComponent(n1, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel6)
        						.addComponent(n2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addGap(17)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel11)
        				.addComponent(n3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(50)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel12)
        						.addComponent(media, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(18)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblBimestre)
        						.addComponent(n4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addPreferredGap(ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
        			.addComponent(btnVoltar)
        			.addContainerGap())
        );
        jPanel1.setLayout(gl_jPanel1);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 405, GroupLayout.PREFERRED_SIZE)
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mudaStatusAluno(double media){
    	if (!n4.getText().equals("") & media >= 6.0){
        	lblCursando.setText("Aprovado");
        }
        else if (!n4.getText().equals("") & media < 6.0){
        	lblCursando.setText("Reprovado");
        }
        else if (n4.getText().equals("")){
        	lblCursando.setText("Cursando");
        }
    	
    }
    
    private void bttnConfirmarPerformed(){
    	System.out.println(n4.getText());
    	if (!n1.getText().equals("")){
    		notas[0] = Double.parseDouble(n1.getText());
    	}
    	else notas[0] = 0.0;
    	if (!n2.getText().equals("")){
    		notas[1] = Double.parseDouble(n2.getText());
    	}
    	else notas[1] = 0.0;
    	if (!n3.getText().equals("")){
    		notas[2] = Double.parseDouble(n3.getText());
    	}
    	else notas[2] = 0.0;
    	if (!n4.getText().equals("")){
    		notas[3] = Double.parseDouble(n4.getText());
    	}
    	else notas[3] = 0.0;
    	
    	if (notas[0] > 10.0 | notas[0] < 0.0){
    		n1.setText("");
    		return;
    	}
    	else if(notas[1] > 10.0 | notas[1] < 0.0){
    		n2.setText("");
    		return;
    	}
    	else if (notas[2] > 10.0 | notas[2] < 0.0){
    		n3.setText("");
    		return;
    	}
    	else if (notas[3] > 10.0 | notas[3] < 0.0){
    		n4.setText("");
    		return;
    	}
    	DecimalFormat numberFormat = new DecimalFormat("#.00");
    	double theMedia = aluno.doMedia(notas[0], notas[1], notas[2], notas[3]);
    	String mediaStr = String.valueOf(numberFormat.format(theMedia));
    	media.setText(mediaStr);
        n1.setEditable(false);
        n1.setBackground(Color.LIGHT_GRAY);
        n2.setEditable(false);
        n2.setBackground(Color.LIGHT_GRAY);
        n3.setEditable(false);
        n3.setBackground(Color.LIGHT_GRAY);
        n4.setEditable(false);
        n4.setBackground(Color.LIGHT_GRAY);
    	mudaStatusAluno(theMedia);
    }
    
    private void recuperarNotasAluno(){
    	String nota = new String();
        if(aluno.getFlag(d,0)){
        	nota = String.valueOf(aluno.getN1(d));
            n1.setText(nota);
            n1.setEditable(false);
            n1.setBackground(Color.LIGHT_GRAY);
        }
        if (aluno.getFlag(d,1)){
        	 nota = String.valueOf(aluno.getN2(d));
             n2.setText(nota);
             n2.setEditable(false);
             n2.setBackground(Color.LIGHT_GRAY);
        }
        if (aluno.getFlag(d,2)){
       	 	nota = String.valueOf(aluno.getN3(d));
            n3.setText(nota);
            n3.setEditable(false);
            n3.setBackground(Color.LIGHT_GRAY);
       }
        if (aluno.getFlag(d,3)){
       	 	nota = String.valueOf(aluno.getN4(d));
            n4.setText(nota);
            n4.setEditable(false);
            n4.setBackground(Color.LIGHT_GRAY);
       }
        DecimalFormat numberFormat = new DecimalFormat("#.00");
        nota = String.valueOf(numberFormat.format(aluno.getMedia(d)));
        media.setText(nota);
        mudaStatusAluno(aluno.getMedia(d));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAlunoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAlunoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAlunoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAlunoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAlunoNotas(aluno, d).setVisible(true);
            }
        });
        
        
    }
    
    
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private JLabel lblCursando;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField media;
    private JButton btnVoltar;
    private JTextField n4;
}
