/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import mainpkg.*;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.Collator;
import java.util.Locale;

import javax.swing.JLabel;
import javax.swing.JTextField;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Ana Luísa, Cauã
 */
public class JanelaProfCadastraDisciplina extends javax.swing.JFrame {
	
	private Cadastro castro;
	private static Disciplina[] disciplinas = new Disciplina[ObjArrays.getFinaldisc()-1];
	private boolean discNonRepeatable = false;
	private JComboBox[] DisciplinasVer = {null, null, null}; //Armazena as disciplinas com nome igual, serve pra verificar as que ainda estão em vermelho e branqueá-las. Pura gambiarra
	private static String area;
	
	public void setCastro(Cadastro castro) {
		this.castro = castro;
	}
	

    /**
     * Creates new form CadastroAluno
     */
    public JanelaProfCadastraDisciplina(String s) {
    	area = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ListaDisc1 = new JComboBox();
        ListaDisc2 = new JComboBox();
        ListaDisc3 = new JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jButton1.setText("Concluir Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        jButton2_1 = new JButton("Voltar");
        jButton2_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		castro.setVisible(true);
        		setVisible(false);
        	}
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disciplinas que Ministrar�", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Escolha no m�nimo uma:");

        jLabel2.setText("A -");

        jLabel3.setText("B -");

        jLabel4.setText("C -");
        
        
        ListaDisc1.setModel(new DefaultComboBoxModel(dropmenu()));
        ListaDisc1.setBackground(Color.WHITE);
       
        ListaDisc2.setModel(new DefaultComboBoxModel(dropmenu()));
        ListaDisc2.setBackground(Color.WHITE);
        
        ListaDisc3.setModel(new DefaultComboBoxModel(dropmenu()));
        ListaDisc3.setBackground(Color.WHITE);
       
        GroupLayout gl_jPanel1 = new GroupLayout(jPanel1);
        gl_jPanel1.setHorizontalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGap(6)
        			.addComponent(jLabel1))
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jLabel2)
        			.addGap(4)
        			.addComponent(ListaDisc1, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
        			.addGap(234))
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jLabel3)
        			.addGap(4)
        			.addComponent(ListaDisc2, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
        			.addGap(235))
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jLabel4)
        			.addGap(4)
        			.addComponent(ListaDisc3, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
        			.addGap(234))
        );
        gl_jPanel1.setVerticalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGap(31)
        			.addComponent(jLabel1)
        			.addGap(12)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel2))
        				.addComponent(ListaDisc1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
        			.addGap(11)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(4)
        					.addComponent(jLabel3))
        				.addComponent(ListaDisc2, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
        			.addGap(11)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(4)
        					.addComponent(jLabel4))
        				.addComponent(ListaDisc3, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
        			.addGap(33))
        );
        jPanel1.setLayout(gl_jPanel1);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(jButton2_1, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        			.addGap(101)
        			.addComponent(jButton1))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton2_1))
        			.addContainerGap())
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean comparaDiscRepetidas(int x){
    	int discNonRepContador = 0;
    	int aux = 0;
    	Collator collator = Collator.getInstance(new Locale("pt","BR"));
    	collator.setStrength(Collator.PRIMARY);
        
        JComboBox[] Disciplinas = new JComboBox[3];
        Disciplinas[0] = ListaDisc1;
        Disciplinas[1] = ListaDisc2;
        Disciplinas[2] = ListaDisc3;
        
        if (Disciplinas[x].getSelectedItem().toString().equals("")) return true;
		for(int i = 0; i < 3; i++){
			
			if (x == i) continue;
			else if (collator.compare(Disciplinas[x].getSelectedItem().toString(), Disciplinas[i].getSelectedItem().toString())==0){
    			Disciplinas[x].setBackground(Color.RED);
    			Disciplinas[i].setBackground(Color.RED);
    			DisciplinasVer[aux] = Disciplinas[i];
    			aux++;
    			discNonRepContador++;
    		}
			else if (collator.compare(Disciplinas[x].getSelectedItem().toString(), Disciplinas[i].getSelectedItem().toString())!=0){
				Disciplinas[i].setBackground(Color.WHITE);
			}
		}
		if (discNonRepContador > 0){
			discNonRepContador = 0;
			return false;
		}
		else {
			Disciplinas[x].setBackground(Color.WHITE);
			for (int i =0; i < 3; i++){
				if (DisciplinasVer[i] != null){
					DisciplinasVer[i].setBackground(Color.WHITE);
					DisciplinasVer[i] = null;
				}
			}
			return true;
		}
    }

    private void setDisciplinas(JComboBox discNome){
    	String nome = discNome.getSelectedItem().toString();
    	if (nome.equals("")){
    		return;
    	}
    	else ObjArrays.adicionarProfDisciplina(ObjArrays.setDisciplinas(nome, area));
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	while(discNonRepeatable == false){
    		if(!comparaDiscRepetidas(0)) break;
    		else if(!comparaDiscRepetidas(1)) break;
    		else if(!comparaDiscRepetidas(2)) break;
    		else if(ListaDisc1.getSelectedItem().toString().equals("") & ListaDisc2.getSelectedItem().toString().equals("")
    				& ListaDisc3.getSelectedItem().toString().equals("")) break;
    		discNonRepeatable = true;
    		
    	}
    	if (discNonRepeatable == true){
    		setDisciplinas(ListaDisc1);
    		setDisciplinas(ListaDisc2);
    		setDisciplinas(ListaDisc3);
    		ObjArrays.terminaProfCadastro();
	        castro.getInicial().setVisible(true);
	        setVisible(false);
    	}
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private String[] dropmenu(){
    	String[] source = ObjArrays.buscaDisciplinaByArea(area);
    	String[] dropdown = new String[source.length+1];
    	dropdown[0] = "";
    	int j = 1;
    	for(int i =0; i < source.length; i++){
    		dropdown[j] = source[i];
    		j++;
    	}
    	return dropdown;    	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaProfCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaProfCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaProfCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaProfCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaProfCadastraDisciplina(area).setVisible(true);
            }
        });
        for(int i = 1; i < (ObjArrays.getFinaldisc()-1); i++){
        	disciplinas[i] = ObjArrays.getDisciplinas(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private JButton jButton2_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private JComboBox ListaDisc1;
    private JComboBox ListaDisc2;
    private JComboBox ListaDisc3;
    private JLabel lblModalidade7;
    private JLabel lblModalidade8;
}
