/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import mainpkg.*;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.DecimalFormat;
import java.util.InputMismatchException;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Ana Luísa
 */
public class NotasAluno extends javax.swing.JFrame {

	
	private static Aluno aluno;
	private ProfSelecionaAluno lastWindow;
	private double[] notas = {0, 0, 0};
	
	public void setLastWindow(ProfSelecionaAluno window){
		this.lastWindow = window;
	}
    /**
     * Creates new form NotasAluno
     */
    public NotasAluno(Aluno aluno) {
    	this.aluno = aluno;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCursando = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        media = new javax.swing.JTextField();
        

        jTextField1.setText("jTextField1");
        

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel14.setText("jLabel14");

        jTextField12.setText("jTextField12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notas de "+aluno.getNome(), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("N1:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("N2:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("N3:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Média:");

        n1.setBackground(Color.WHITE);
        n1.setFont(new java.awt.Font("Tahoma", 0, 12));
        n1.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		try {
        		  double usrInput= Double.parseDouble(n1.getText());
        		}
        		catch(NumberFormatException exception) {
        		  System.out.println("This is not a double");
        		  n1.setText("");
        		}
        	}
        });

        n2.setBackground(Color.WHITE);
        n2.setFont(new java.awt.Font("Tahoma", 0, 12));
        n2.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		try {
          		  double usrInput= Double.parseDouble(n2.getText());
          		}
          		catch(NumberFormatException exception) {
          		  System.out.println("This is not a double");
          		  n2.setText("");
          		}
        	}
        });

        n3.setBackground(Color.WHITE);
        n3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        n3.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		try {
          		  double usrInput= Double.parseDouble(n3.getText());
          		}
          		catch(NumberFormatException exception) {
          		  System.out.println("This is not a double");
          		  n3.setText("");
          		}
        	}
        });
        
        
        media.setBackground(new java.awt.Color(240, 240, 240));
        media.setEditable(false);
        media.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 304, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);
        
        lblCursando.setText("Cursando");
        lblCursando.setFont(new Font("Dialog", Font.BOLD, 20));
        
        JButton btnVoltar = new JButton("Voltar");
        
        JButton btnAlterarNotas = new JButton("Alterar Notas");
        btnAlterarNotas.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bttnAlterarPerformed();
        	}
        });
        
        JButton btnNewButton = new JButton("Enviar Notas");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bttnEnviarPerformed();
        	}
        });
        
        JButton btnVerMdia = new JButton("Confirmar Notas");
        btnVerMdia.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bttnConfirmarPerformed();
        	}
        });
        GroupLayout gl_jPanel1 = new GroupLayout(jPanel1);
        gl_jPanel1.setHorizontalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblCursando, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel12)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(media, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)))
        					.addGap(81)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addGap(26)
        							.addComponent(n1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(26)
        							.addComponent(n2, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel11)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(n3, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addComponent(btnVoltar)
        					.addGap(29)
        					.addComponent(btnAlterarNotas)
        					.addGap(18)
        					.addComponent(btnNewButton)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
        			.addContainerGap(253, Short.MAX_VALUE)
        			.addComponent(btnVerMdia)
        			.addContainerGap())
        );
        gl_jPanel1.setVerticalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(12)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addGap(2)
        							.addComponent(jLabel4))
        						.addComponent(n1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(12)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addGap(2)
        							.addComponent(jLabel6))
        						.addComponent(n2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(24)
        					.addComponent(lblCursando, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)))
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel11)
        						.addComponent(n3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(31)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel12)
        						.addComponent(media, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addGap(59)
        			.addComponent(btnVerMdia)
        			.addGap(18)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnVoltar)
        				.addComponent(btnAlterarNotas)
        				.addComponent(btnNewButton))
        			.addContainerGap())
        );
        jPanel1.setLayout(gl_jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bttnConfirmarPerformed(){
    	System.out.println(n3.getText());
    	if (!n1.getText().equals("")){
    		notas[0] = Double.parseDouble(n1.getText());
    	}
    	else notas[0] = 0.0;
    	if (!n2.getText().equals("")){
    		notas[1] = Double.parseDouble(n2.getText());
    	}
    	else notas[1] = 0.0;
    	if (!n3.getText().equals("")){
    		notas[2] = Double.parseDouble(n3.getText());
    	}
    	else notas[2] = 0.0;
    	
    	if (notas[0] > 10.0 | notas[0] < 0.0){
    		n1.setText("");
    		return;
    	}
    	else if(notas[1] > 10.0 | notas[1] < 0.0){
    		n2.setText("");
    		return;
    	}
    	else if (notas[2] > 10.0 | notas[2] < 0.0){
    		n3.setText("");
    		return;
    	}
    	DecimalFormat numberFormat = new DecimalFormat("#.00");
    	double theMedia = aluno.getMedia(notas[0], notas[1], notas[2]);
    	String mediaStr = String.valueOf(numberFormat.format(theMedia));
    	media.setText(mediaStr);
        n1.setEditable(false);
        n1.setBackground(Color.LIGHT_GRAY);
        n2.setEditable(false);
        n2.setBackground(Color.LIGHT_GRAY);
        n3.setEditable(false);
        n3.setBackground(Color.LIGHT_GRAY);
        
        if (!n3.getText().equals("") & theMedia >= 6.0){
        	lblCursando.setText("Aprovado");
        }
        else if (!n3.getText().equals("") & theMedia < 6.0){
        	lblCursando.setText("Reprovado");
        }
        else if (n3.getText().equals("")){
        	lblCursando.setText("Cursando");
        }
    	
    }
    
    private void bttnAlterarPerformed(){
    	n1.setEditable(true);
        n1.setBackground(Color.WHITE);
        n2.setEditable(true);
        n2.setBackground(Color.WHITE);
        n3.setEditable(true);
        n3.setBackground(Color.WHITE);
    }
    
    private void bttnEnviarPerformed(){
    	bttnConfirmarPerformed();
    	aluno.setNotas(notas[0], notas[1], notas[2]);
    }

    private void mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaActionPerformed
        //consultaDisciplinas
    }//GEN-LAST:event_mediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotasAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotasAluno(aluno).setVisible(true);
            }
        });
    }
    
    
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private JLabel lblCursando;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField media;
}
