/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import mainpkg.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.JPasswordField;

/**
 *
 * @authors Ana Luísa e Paula
 */
public class PrimeiraJanela extends javax.swing.JFrame {

    /**
     * Creates new form PrimeiraJanela
     */
    public PrimeiraJanela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bttnEntrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bttnCadastre = new javax.swing.JButton();
        bttnSair = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bem Vindo!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        matricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matricula.setName("");

        jLabel2.setText("Matr\u00EDcula");

        jLabel3.setText("Senha");

        bttnEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttnEntrar.setText("Entrar");
        bttnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEntrarActionPerformed(evt);
            }
        });

        jLabel4.setText("N\u00E3o possui cadastro?");

        bttnCadastre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttnCadastre.setText("Cadastre-se");
        bttnCadastre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCadastreActionPerformed(evt);
            }
        });

        bttnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttnSair.setText("Sair");
        bttnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSairActionPerformed(evt);
            }
        });
        
        senha = new JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(bttnCadastre)
        			.addPreferredGap(ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
        			.addComponent(bttnSair)
        			.addContainerGap())
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(283)
        					.addComponent(jLabel1))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(103)
        					.addComponent(bttnEntrar))
        				.addComponent(jLabel4)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(79)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(senha, Alignment.LEADING)
        						.addComponent(matricula, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
        			.addGap(0, 0, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(107)
        			.addComponent(jLabel2)
        			.addContainerGap(110, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(114)
        			.addComponent(jLabel3)
        			.addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(28)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(matricula, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(19)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(senha, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(bttnEntrar, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(bttnCadastre)
        				.addComponent(bttnSair))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void bttnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSairActionPerformed
    	
    	try {
			FileOutputStream fout = new FileOutputStream("dados.txt");
	    	ObjectOutputStream oos = new ObjectOutputStream(fout);
	    	oos.writeObject(ObjArrays.getProfessores());
	    	oos.writeObject(ObjArrays.getDisciplinas());
	    	oos.writeObject(ObjArrays.getAlunos());
	    	oos.writeInt(ObjArrays.getFinalProf());
	    	oos.writeInt(ObjArrays.getFinaldisc());
	    	oos.writeInt(ObjArrays.getFinalAlun());
	    	oos.close();
	    	System.out.println("DONE");
    	}
    	catch(Exception ex){
    		ex.printStackTrace();
    	}
    	
        System.exit(0);
    }//GEN-LAST:event_bttnSairActionPerformed

    private void bttnEntrarActionPerformed(java.awt.event.ActionEvent evt) {
    	//GEN-FIRST:event_bttnEntrarActionPerformed
    	String strSenha = new String(senha.getPassword());
    	if (matricula.getText().length() == 8){
    		Professor prof = validaCadastroProf(matricula.getText(), strSenha);
    		if (prof != null) {
    			ProfConsultaDisciplina disc = new ProfConsultaDisciplina(prof);
    			disc.setInicial(this);
    			disc.setVisible(true);
    			setVisible(false);
    		}
    	}
    	else if (matricula.getText().length() == 10){
    		if (validaCadastroAluno(matricula.getText(), strSenha) != null) {
    			EmConstrucao emcons = new EmConstrucao();
    			emcons.setVisible(true);
    			setVisible(false);
    		}
    	}
    	
    }//GEN-LAST:event_bttnEntrarActionPerformed

    private void bttnCadastreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCadastreActionPerformed
       //chama a proxima janela
        AlunoOrProf alunoorprof = new AlunoOrProf();
        alunoorprof.setIniciar(this);
        alunoorprof.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bttnCadastreActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * 
     */

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeiraJanela().setVisible(true);
            }
        });
        
        /*ObjArrays.setDisciplinas("Língua Portuguesa I", "Humanas");
        ObjArrays.setDisciplinas("Geografia Fisica I", "Humanas");
        ObjArrays.setDisciplinas("História do Brasil I", "Humanas");
        ObjArrays.setDisciplinas("Filosofia I", "Humanas");
        ObjArrays.setDisciplinas("Sociologia I", "Humanas");
        ObjArrays.setDisciplinas("Lingua Inglesa I", "Humanas");
        ObjArrays.setDisciplinas("Matemática Básica I", "Exatas");
        ObjArrays.setDisciplinas("Física Elétrica I", "Exatas");
        ObjArrays.setDisciplinas("Química Orgânica I", "Exatas");
        ObjArrays.setDisciplinas("Ecologia I", "Biológicas");
        ObjArrays.setDisciplinas("Genética I", "Biológicas");
        ObjArrays.setDisciplinas("Bioquímica I", "Biológicas");*/
        try {
    		FileInputStream fin = new FileInputStream("dados.txt");
	    	ObjectInputStream ois = new ObjectInputStream(fin);
	    	//ObjArrays objeto = (ObjArrays) ois.readObject();
	    	ObjArrays.setProfessoresArray((ArrayList<Professor>) ois.readObject());
	    	ObjArrays.setDisciplinasArray((ArrayList<Disciplina>) ois.readObject());
	    	ObjArrays.setAlunosArray((ArrayList<Aluno>) ois.readObject());
	    	ObjArrays.setFinalProf(ois.readInt());
	    	ObjArrays.setFinalDisc(ois.readInt());
	    	ObjArrays.setFinalAlun(ois.readInt());
	    	ois.close();
	    	System.out.println(ObjArrays.getProfessores().get(0).getMatricula());
    	}
    	catch (Exception ex){
    		ex.printStackTrace();
    	}
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCadastre;
    private javax.swing.JButton bttnEntrar;
    private javax.swing.JButton bttnSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matricula;
    private JPasswordField senha;
    // End of variables declaration//GEN-END:variables


    private Professor validaCadastroProf(String matricula, String senha) {
        Professor prof = ObjArrays.buscaProfessor(matricula);
        if (prof != null){
        	if (senha.equals(prof.getSenha())){
        		return prof;
        	}
        	else return null;
        }
        else return null;

    }
    
    private Aluno validaCadastroAluno(String matricula, String senha) {
        Aluno aluno = ObjArrays.buscaAluno(matricula);
        if (aluno != null){
        	if (senha.equals(aluno.getSenha())){
        		return aluno;
        	}
        	else return null;
        }
        else return null;

    }
}
