/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import mainpkg.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.JPasswordField;
import java.awt.Font;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 *
 * @authors Ana Luísa e Paula
 */
public class PrimeiraJanela extends javax.swing.JFrame {

    /**
     * Creates new form PrimeiraJanela
     */
    public PrimeiraJanela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        matricula.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent arg0) {
        		senhaIncorreta.setText("");
        	}
        });
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 12));
        bttnEntrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 14));
        bttnCadastre = new javax.swing.JButton();
        bttnSair = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bem Vindo!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        matricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matricula.setName("");

        jLabel2.setText("Matr\u00EDcula");

        jLabel3.setText("Senha");

        bttnEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttnEntrar.setText("Entrar");
        bttnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEntrarActionPerformed(evt);
            }
        });

        jLabel4.setText("N\u00E3o possui cadastro?");

        bttnCadastre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttnCadastre.setText("Cadastre-se");
        bttnCadastre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCadastreActionPerformed(evt);
            }
        });

        bttnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttnSair.setText("Sair");
        bttnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSairActionPerformed(evt);
            }
        });
        
        senha = new JPasswordField();
        senha.setHorizontalAlignment(SwingConstants.CENTER);
        senha.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent e) {
        		senhaIncorreta.setText("");
        	}
        });
        
        JSeparator separator = new JSeparator();
        separator.setOrientation(SwingConstants.VERTICAL);
        
        JLabel lblEntreComSuas = new JLabel();
        lblEntreComSuas.setText("Entre com suas credenciais");
        lblEntreComSuas.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        senhaIncorreta = new JLabel("");
        senhaIncorreta.setForeground(Color.RED);
        GroupLayout gl_jPanel1 = new GroupLayout(jPanel1);
        gl_jPanel1.setHorizontalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGap(283)
        					.addComponent(jLabel1))
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addContainerGap(54, Short.MAX_VALUE)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addGroup(Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addGap(41))
        						.addGroup(Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
        							.addComponent(bttnCadastre, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE)
        							.addGap(55)))
        					.addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addGap(50)
        							.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        								.addComponent(senha, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        								.addComponent(matricula, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addGap(75)
        							.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        								.addComponent(senhaIncorreta)
        								.addComponent(bttnEntrar)))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addGap(18)
        							.addGroup(gl_jPanel1.createParallelGroup(Alignment.TRAILING)
        								.addComponent(bttnSair)
        								.addComponent(lblEntreComSuas)))
        						.addGroup(Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
        							.addGap(55))
        						.addGroup(Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        							.addGap(66)))))
        			.addGap(210))
        );
        gl_jPanel1.setVerticalGroup(
        	gl_jPanel1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel1.createSequentialGroup()
        			.addGap(11)
        			.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        				.addComponent(separator, GroupLayout.PREFERRED_SIZE, 243, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_jPanel1.createSequentialGroup()
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(jLabel1)
        							.addGap(19)
        							.addComponent(lblEntreComSuas, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addGap(19)
        							.addComponent(jLabel4)))
        					.addGap(18)
        					.addComponent(jLabel2)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(gl_jPanel1.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_jPanel1.createSequentialGroup()
        							.addComponent(matricula, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jLabel3)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(senha, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(bttnEntrar, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        						.addComponent(bttnCadastre, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(senhaIncorreta)))
        			.addGap(29))
        		.addGroup(Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
        			.addContainerGap(249, Short.MAX_VALUE)
        			.addComponent(bttnSair)
        			.addContainerGap())
        );
        jPanel1.setLayout(gl_jPanel1);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 431, GroupLayout.PREFERRED_SIZE)
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void bttnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSairActionPerformed
    	
    	try {
			FileOutputStream fout = new FileOutputStream("dados.txt");
	    	ObjectOutputStream oos = new ObjectOutputStream(fout);
	    	oos.writeObject(ObjArrays.getProfessores());
	    	oos.writeObject(ObjArrays.getDisciplinas());
	    	oos.writeObject(ObjArrays.getAlunos());
	    	oos.writeInt(ObjArrays.getFinalProf());
	    	oos.writeInt(ObjArrays.getFinaldisc());
	    	oos.writeInt(ObjArrays.getFinalAlun());
	    	oos.writeObject(ObjArrays.getDiscArray());
	    	oos.close();
	    	System.out.println("DONE");
    	}
    	catch(Exception ex){
    		ex.printStackTrace();
    	}
    	
        System.exit(0);
    }//GEN-LAST:event_bttnSairActionPerformed

    private void bttnEntrarActionPerformed(java.awt.event.ActionEvent evt) {
    	//GEN-FIRST:event_bttnEntrarActionPerformed
    	String strSenha = new String(senha.getPassword());
    	if (matricula.getText().length() == 8){
    		Professor prof = validaCadastroProf(matricula.getText(), strSenha);
    		if (prof != null) {
    			ProfConsultaDisciplina janelanovaprof = new ProfConsultaDisciplina(prof);
    			janelanovaprof.setInicial(this);
    			janelanovaprof.setVisible(true);
    			senha.setText("");
    			setVisible(false);
    		}
    	}
    	else if (matricula.getText().length() == 10){
    		Aluno aluno = validaCadastroAluno(matricula.getText(), strSenha);
    		if (aluno != null) {
    			JanelaAlunoSelecDisciplina janelanova = new JanelaAlunoSelecDisciplina(aluno);
    			janelanova.setInicial(this);
    			janelanova.setVisible(true);
    			senha.setText("");
    			setVisible(false);
    		}
    	}
    	
    }//GEN-LAST:event_bttnEntrarActionPerformed

    private void bttnCadastreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCadastreActionPerformed
       //chama a proxima janela
        AlunoOrProf alunoorprof = new AlunoOrProf();
        alunoorprof.setIniciar(this);
        alunoorprof.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bttnCadastreActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * 
     */

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeiraJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeiraJanela().setVisible(true);
            }
        });
        
        /*ObjArrays.setDisciplinas("Língua Portuguesa I", "Humanas");
        ObjArrays.setDisciplinas("Geografia Fisica I", "Humanas");
        ObjArrays.setDisciplinas("História do Brasil I", "Humanas");
        ObjArrays.setDisciplinas("Filosofia I", "Humanas");
        ObjArrays.setDisciplinas("Sociologia I", "Humanas");
        ObjArrays.setDisciplinas("Lingua Inglesa I", "Humanas");
        ObjArrays.setDisciplinas("Matemática Básica I", "Exatas");
        ObjArrays.setDisciplinas("Física Elétrica I", "Exatas");
        ObjArrays.setDisciplinas("Química Orgânica I", "Exatas");
        ObjArrays.setDisciplinas("Ecologia I", "Biológicas");
        ObjArrays.setDisciplinas("Genética I", "Biológicas");
        ObjArrays.setDisciplinas("Bioquímica I", "Biológicas");*/
        try {
    		FileInputStream fin = new FileInputStream("dados.txt");
	    	ObjectInputStream ois = new ObjectInputStream(fin);
	    	//ObjArrays objeto = (ObjArrays) ois.readObject();
	    	ObjArrays.setProfessoresArray((ArrayList<Professor>) ois.readObject());
	    	ObjArrays.setDisciplinasArray((ArrayList<Disciplina>) ois.readObject());
	    	System.out.println(ObjArrays.getDisciplinas().get(0).getNome());
	    	ObjArrays.setAlunosArray((ArrayList<Aluno>) ois.readObject());
	    	ObjArrays.setFinalProf(ois.readInt());
	    	ObjArrays.setFinalDisc(ois.readInt());
	    	ObjArrays.setFinalAlun(ois.readInt());
	    	ObjArrays.setDiscArray((String[])ois.readObject());
	    	ois.close();
	    	System.out.println(ObjArrays.getProfessores().get(0).getMatricula());
    	}
    	catch (Exception ex){
    		ex.printStackTrace();
    	}
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCadastre;
    private javax.swing.JButton bttnEntrar;
    private javax.swing.JButton bttnSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matricula;
    private JPasswordField senha;
    private JLabel senhaIncorreta;
    // End of variables declaration//GEN-END:variables


    private Professor validaCadastroProf(String matricula, String senha) {
        Professor prof = ObjArrays.buscaProfessor(matricula);
        if (prof != null){
        	if (senha.equals(prof.getSenha())){
        		return prof;
        	}
        	else {
        		senhaIncorreta.setText("Senha Incorreta!");
        		return null;
        	}
        }
        else {
        	senhaIncorreta.setText("Matr�cula inexistente!");
        	return null;
        }

    }
    
    private Aluno validaCadastroAluno(String matricula, String senha) {
        Aluno aluno = ObjArrays.buscaAluno(matricula);
        if (aluno != null){
        	if (senha.equals(aluno.getSenha())){
        		return aluno;
        	}
        	else {
        		senhaIncorreta.setText("Senha Incorreta!");
        		return null;
        	}
        }
        else {
        	senhaIncorreta.setText("Matr�cula inexistente!");
        	return null;
        }

    }
}
